export type Product = {
  id: string;
  name: string;
  price: number;
  stock: number;
  scale: string; // Difungsikan sebagai: Grade / Kualitas / Form
  material: string; // Difungsikan sebagai: Strain / Varietas Genetik
  year: number; // Difungsikan sebagai: Ukuran (cm)
  image: string;
  category: string;
  badge: "New Arrival" | "Limited Edition" | null;
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "gpy-001",
    name: "Guppy Albino Full Red (AFR)",
    price: 75000,
    stock: 25,
    scale: "Pair (M-F)",
    material: "Pure Strain Albino",
    year: 3,
    image: "/images/guppy-afr.jpg",
    category: "Guppy",
    badge: "New Arrival",
  },
  {
    id: "gpy-002",
    name: "Guppy Blue Grass High Fin",
    price: 150000,
    stock: 6,
    scale: "Grade A+",
    material: "Ribbon Swallow Gen",
    year: 4,
    image: "/images/guppy-bluegrass.jpg",
    category: "Guppy",
    badge: "Limited Edition",
  },
  {
    id: "gpy-003",
    name: "Guppy Purple Mosaic",
    price: 95000,
    stock: 15,
    scale: "Pair (M-F)",
    material: "Dark Violet Tail",
    year: 3,
    image: "/images/guppy-purple-mosaic.jpg",
    category: "Guppy",
    badge: null,
  },
  {
    id: "gpy-004",
    name: "Guppy Dragon Big Ear",
    price: 120000,
    stock: 10,
    scale: "Grade S",
    material: "Dumbo Ear Gen",
    year: 4,
    image: "/images/guppy-dragon.jpg",
    category: "Guppy",
    badge: "New Arrival",
  },
  {
    id: "mly-001",
    name: "Black Moscow Molly",
    price: 15000,
    stock: 50,
    scale: "Grade A",
    material: "Solid Midnight Black",
    year: 5,
    image: "/images/molly-black.jpg",
    category: "Molly",
    badge: null,
  },
  {
    id: "mly-002",
    name: "Golden Balloon Molly",
    price: 25000,
    stock: 30,
    scale: "Short Body",
    material: "Platinum Yellow Speckle",
    year: 4,
    image: "/images/molly-balloon.jpg",
    category: "Molly",
    badge: "New Arrival",
  },
  {
    id: "mly-003",
    name: "White Platinum Lyretail Molly",
    price: 35000,
    stock: 18,
    scale: "Grade S",
    material: "Snow White Reflective",
    year: 6,
    image: "/images/molly-platinum.jpg",
    category: "Molly",
    badge: null,
  },
  {
    id: "mly-004",
    name: "Marble Sailfin Molly",
    price: 45000,
    stock: 12,
    scale: "High Fin Premium",
    material: "Calico Dalmatian Strain",
    year: 7,
    image: "/images/molly-marble.jpg",
    category: "Molly",
    badge: "Limited Edition",
  },
  {
    id: "ttr-001",
    name: "Neon Tetra Glow",
    price: 8000,
    stock: 200,
    scale: "Colony Pack",
    material: "Paracheirodon Innesi",
    year: 2,
    image: "/images/neon-tetra.jpg",
    category: "Tetra",
    badge: null,
  },
  {
    id: "ttr-002",
    name: "Cardinal Tetra Premium XL",
    price: 12000,
    stock: 150,
    scale: "Wild Caught Look",
    material: "Cheirodon Axelrodi",
    year: 3,
    image: "/images/cardinal-tetra.jpg",
    category: "Tetra",
    badge: "New Arrival",
  },
  {
    id: "ttr-003",
    name: "Rummy Nose Tetra",
    price: 15000,
    stock: 80,
    scale: "Schooling Pack",
    material: "Hemigrammus Rhodostomus",
    year: 4,
    image: "/images/rummynose.jpg",
    category: "Tetra",
    badge: null,
  },
  {
    id: "ttr-004",
    name: "Ember Tetra Fire Red",
    price: 10000,
    stock: 120,
    scale: "Nano Selected",
    material: "Hyphessobrycon Amandae",
    year: 2,
    image: "/images/ember-tetra.jpg",
    category: "Tetra",
    badge: "Limited Edition",
  },
  {
    id: "pty-001",
    name: "Platy Santa Claus High Fin",
    price: 35000,
    stock: 12,
    scale: "Grade S",
    material: "Tricolor Variatus",
    year: 4,
    image: "/images/platy-santa.jpg",
    category: "Platy",
    badge: "Limited Edition",
  },
  {
    id: "pty-002",
    name: "Mickey Mouse Red Platy",
    price: 12000,
    stock: 40,
    scale: "Grade A",
    material: "Classic Caudal Pattern",
    year: 4,
    image: "/images/platy-mickey.jpg",
    category: "Platy",
    badge: null,
  },
  {
    id: "pty-003",
    name: "Bumblebee Platy",
    price: 18000,
    stock: 25,
    scale: "Short Form",
    material: "Tiger Stripe Yellow",
    year: 3,
    image: "/images/platy-bumblebee.jpg",
    category: "Platy",
    badge: "New Arrival",
  },
  {
    id: "rsb-001",
    name: "Harlequin Rasbora",
    price: 9000,
    stock: 90,
    scale: "Colony Grade",
    material: "Trigonostigma Heteromorpha",
    year: 3,
    image: "/images/harlequin.jpg",
    category: "Rasbora",
    badge: null,
  },
  {
    id: "rsb-002",
    name: "Galaxy Rasbora (Celestial Pearl)",
    price: 45000,
    stock: 35,
    scale: "Exotic Grade A",
    material: "Danio Margaritatus",
    year: 2,
    image: "/images/galaxy-rasbora.jpg",
    category: "Rasbora",
    badge: "Limited Edition",
  },
  {
    id: "bta-001",
    name: "Wild Betta Mahachaiensis",
    price: 250000,
    stock: 4,
    scale: "Show Grade",
    material: "Pure Green Metallic Wild",
    year: 5,
    image: "/images/betta-mahachai.jpg",
    category: "Wild Betta",
    badge: "Limited Edition",
  },
  {
    id: "bta-002",
    name: "Wild Betta Alien Blue",
    price: 175000,
    stock: 7,
    scale: "Pair Ready",
    material: "Alien Hybrid Cross",
    year: 5,
    image: "/images/betta-alien.jpg",
    category: "Wild Betta",
    badge: "New Arrival",
  },
  {
    id: "shm-001",
    name: "Caridina Blue Dream Shrimp",
    price: 15000,
    stock: 100,
    scale: "Invertebrate Pack",
    material: "Solid Velvet Blue",
    year: 1,
    image: "/images/shrimp-blue.jpg",
    category: "Shrimp",
    badge: null,
  },
];
